version: "3.7"
services:
  app:
    container_name: movie-apps
    restart : always
    build : .
    ports:
    - "4040:4040"
    links:
    - mongo
  mongo:
    container_name : mongoDB
    image: mongo
    ports:
    - "27017:27017"
